import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "black-50": "rgb(var(--color-black-50) / <alpha-value>)",
        "black-900": "rgb(var(--color-black-900) / <alpha-value>)",
        "cyan-100": "rgb(var(--color-cyan-100) / <alpha-value>)",
        "cyan-200": "rgb(var(--color-cyan-200) / <alpha-value>)",
        "cyan-300": "rgb(var(--color-cyan-300) / <alpha-value>)",
        "cyan-400": "rgb(var(--color-cyan-400) / <alpha-value>)",
        "cyan-500": "rgb(var(--color-cyan-500) / <alpha-value>)",
        "cyan-600": "rgb(var(--color-cyan-600) / <alpha-value>)",
        "indigo-100": "rgb(var(--color-indigo-100) / <alpha-value>)",
        "indigo-200": "rgb(var(--color-indigo-200) / <alpha-value>)",
        "indigo-300": "rgb(var(--color-indigo-300) / <alpha-value>)",
        "indigo-400": "rgb(var(--color-indigo-400) / <alpha-value>)",
        "indigo-500": "rgb(var(--color-indigo-500) / <alpha-value>)",
        "indigo-600": "rgb(var(--color-indigo-600) / <alpha-value>)",
        "purple-100": "rgb(var(--color-purple-100) / <alpha-value>)",
        "purple-200": "rgb(var(--color-purple-200) / <alpha-value>)",
        "purple-300": "rgb(var(--color-purple-300) / <alpha-value>)",
        "purple-400": "rgb(var(--color-purple-400) / <alpha-value>)",
        "purple-500": "rgb(var(--color-purple-500) / <alpha-value>)",
        "purple-600": "rgb(var(--color-purple-600) / <alpha-value>)",
        "red-100": "rgb(var(--color-red-100) / <alpha-value>)",
        "red-200": "rgb(var(--color-red-200) / <alpha-value>)",
        "red-300": "rgb(var(--color-red-300) / <alpha-value>)",
        "red-400": "rgb(var(--color-red-400) / <alpha-value>)",
        "red-500": "rgb(var(--color-red-500) / <alpha-value>)",
        "red-600": "rgb(var(--color-red-600) / <alpha-value>)",
        "yellow-100": "rgb(var(--color-yellow-100) / <alpha-value>)",
        "yellow-200": "rgb(var(--color-yellow-200) / <alpha-value>)",
        "yellow-300": "rgb(var(--color-yellow-300) / <alpha-value>)",
        "yellow-400": "rgb(var(--color-yellow-400) / <alpha-value>)",
        "yellow-500": "rgb(var(--color-yellow-500) / <alpha-value>)",
        "yellow-600": "rgb(var(--color-yellow-600) / <alpha-value>)",
        "green-100": "rgb(var(--color-green-100) / <alpha-value>)",
        "green-200": "rgb(var(--color-green-200) / <alpha-value>)",
        "green-300": "rgb(var(--color-green-300) / <alpha-value>)",
        "green-400": "rgb(var(--color-green-400) / <alpha-value>)",
        "green-500": "rgb(var(--color-green-500) / <alpha-value>)",
        "green-600": "rgb(var(--color-green-600) / <alpha-value>)",
      },
    },
  },
};
export default config;
